version: '2'
services:
  consul:
    command: -server -bootstrap
    image: progrium/consul:latest
    container_name: 'consul'
    ports:
      - "8500:8500"
    environment:
      SERVICE_53_IGNORE: 'yes'
      SERVICE_8300_IGNORE: 'yes'
      SERVICE_8301_IGNORE: 'yes'
      SERVICE_8302_IGNORE: 'yes'
      SERVICE_8400_IGNORE: 'yes'
      SERVICE_8500_NAME: 'consul-admin_infra'
  registrator:
    command: "-internal consul://consul:8500"
    image: gliderlabs/registrator:latest
    container_name: 'registrator'
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
  web:
    build: ./docker/nginx
    container_name: 'web'
    volumes:
    - ./shared/www/shop:/var/www/shop
    ports:
    - "80:80"
    links:
      - order
      - order-process
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.10.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "order:1:1"
    depends_on:
      - zookeeper
  order:
    build: ./services/order-service
    #ports:
    #  - "8080:8081"
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
    depends_on:
      - kafka
  order-process:
    build: ./services/order-process-service
    #ports:
    #  - "8084:8084"
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
    depends_on:
      - kafka
  billing:
    build: ./services/billing-service
    #ports:
    #  - "8081:8081"
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
    depends_on:
      - kafka
  shipping:
    build: ./services/shipping-service
    #ports:
    #  - "8082:8082"
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
    depends_on:
      - kafka
  stock:
    build: ./services/stock-service
    #ports:
    #  - "8083:8083"
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
    depends_on:
      - kafka