version: '2'
services:
  web:
    image: nginx
    #volumes:
    #- ./mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=store.sample.com
    - NGINX_PORT=80
    #command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.10.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "order:1:1"
    depends_on:
      - zookeeper
  order:
    build: ../services/order-service
    ports:
      - "8080:8081"
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
    depends_on:
      - kafka
  order-process:
    build: ../services/order-process-service
    ports:
      - "8084:8084"
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
    depends_on:
      - kafka
  billing:
    build: ../services/billing-service
    ports:
      - "8081:8081"
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
    depends_on:
      - kafka
  shipping:
    build: ../services/shipping-service
    ports:
      - "8082:8082"
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
    depends_on:
      - kafka
  stock:
    build: ../services/stock-service
    ports:
      - "8083:8083"
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
    depends_on:
      - kafka