server:
  port: 8080
spring:
  application:
    name: order-service
  main:
    banner-mode: "off"
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    driverClassName: org.h2.Driver
    username: demoworkflow
    password: demoworkflow
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show-sql: true
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: create-drop
  dao:
    exceptiontranslation:
      enabled: true      
  kafka:
    client-id: order-service
    bootstrap-servers:
      - localhost:9092
    template:
      default-topic: order
    #listener:
    #  ack-mode: manual
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: order
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #enable-auto-commit: false