server:
  port: 8085
spring:
  application:
    name: shop-service
  main:
    banner-mode: "off"
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    driverClassName: org.h2.Driver
    username: demo
    password: demo
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: none
  dao:
    exceptiontranslation:
      enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
  cloud:
    consul:
      enabled: false
      host: consul
      port: 8500
      discovery:
        health-check-path: /shop/health
        fail-fast: false
flyway:
#  enabled: false
  locations:
    - classpath:db/migration
    - classpath:db/data